### ISSUE TITLE
Improve initialization to correctly use default values

### ISSUE THREAD

**Issue by dsmithni** [TBDFramework/StandardEngine#14]
Currently default values are hard to get right. Tags may have a default value and channels may also have a default value, but certain of these values are immediately stomped on as soon as the engine starts running. I think we should deliberately coalesce default values from channels and tags into a single set of defaults which make sense.

**Comment by dsmithni** [comment]
On the other hand tags are easy to set defaults for, while its much much more difficult to make sure every module sets a default. Would it make sense to have a property which indicates if defaults are settable? If yes, then the init function will perform an initial mapping to copy the module's defaults into the engine. If not, then the engine defaults are used? 

Or perhaps we say the reverse -- channels never have defaults, but tags do, and so the 'default' for any channel is the default for any tag it is mapped to, reader *or* writer. This kind of makes sense to me, as we're defining tags as our system dataset. This leaves the 'unmapped channels' use case intact, as any unmapped channels will not even be detected by the engine.

**Comment by Beazurt** [comment]
From the ease-of-use standpoint, we could have a list of unmapped channels in the editor, and allow people to specify defaults for them there.  Especially for those that are inputs to a logical function.  All mapped channels would then use the default in the Tag.  The only case this wouldn't cover is the default value returned by a mapped 'Input' channel.

**Comment by Beazurt** [comment]
"Or perhaps we say the reverse -- channels never have defaults, but tags do, and so the 'default' for any channel is the default for any tag it is mapped to, reader or writer. This kind of makes sense to me, as we're defining tags as our system dataset. This leaves the 'unmapped channels' use case intact, as any unmapped channels will not even be detected by the engine."

This is what got implemented and what I think makes the most sense.  It is really painful to make each module manage their own defaults.  The only time they should really care is when they have an unmapped parameter.  For this case the module must still take responsibility for setting that default properly, but in the future we could have the engine also populate a list of unmapped parameters and allow users to change their value at runtime (like changing PID gains for example).
