### ISSUE TITLE
ns since last call should measure timing with higher fidelity than the dt

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/StandardEngine#37]
Currently we return this value by multiplying dt by the timing source period in ns.  I don't think this gives us any information over the late count.  Instead we should use the tick count VIs and actually measure the loop execution time.

**Comment by dsmithni** [comment]
https://github.com/TBDFramework/StandardEngine/commit/28b2b73cb6026bf12d04c9c2c35f15123ee39768
