### ISSUE TITLE
replace main while loop with event loop

### ISSUE THREAD

**Issue by dsmithni** [TBDFramework/StandardEngine#38]
potentially not feasible, but it could make some things really convenient. Since event structures have priority now, we can use a high priority user event as the main "timing pulse" and it could come from any source we specify, just as it does now (or even an external source) but it could also accept other (lower priority) configuration events. For example the idea of throwing objects to a parallel thread for reinitializing when they fail would be a paiiiin to do in our current implementation -- we'd have yet another queue, yet another thing we have to check if empty, etc. But if we had a low priority event, oh hey we have dataflow *and* an async event. This could also be used for state transitions (abort would be high priority as well, and could potentially be thrown by anyone).

Assuming determinism checks out this could be basically free.

**Comment by dsmithni** [comment]
Determinism seems to be OK. About 50 usec for a 1000 usec tick on a 9068 which is about as good as we could get otherwise.


To my last point -- just keep the timer thread at slightly lower priority than the UI handler. We can also do the reverse and use a flush function, but it seems simpler to say that the main loop needs to run to completion before we check timing again.

**Comment by dsmithni** [comment]
ok, actually, stuff gets weird when you add in other loops (to utilize the CPU). Not sure whats happening anymore.

**Comment by Beazurt** [comment]
Hmm, is the main event loop running at a higher priority than the other loops?  Also how does this affect our timing source implementation.  Would we want to base it off of user events, or convert a timing source as implemented now into the firing of a user event?

**Comment by dsmithni** [comment]
i just converting timing as-is into a loop and I think thats probably right. Would technically use less CPU to make the timing source into its own loop, but meh.

I had 3 loops. priority 65000 was the main loop, 64999 is the timer loop, 1 is the cpu loader. Seems to have weird delays.

**Comment by dsmithni** [comment]
not deterministic, closing
