### ISSUE TITLE
Engine Requires VI Front Panels to Function as an EXE

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/StandardEngine#46]
Get and Set Control methods are used in a few places in the engine.  These don't work if Front Panels get removed which is the default behavior for most build specifications.

**Comment by Beazurt** [comment]
We could use a named queue and enqueue parameters as though it were a stack.  Every time we spawn a worker we pass parameters in the queue.  Workers only pop one value off.  Not as robust as what we have now, but could be an alternative to the asynchronous call.

**Comment by dsmithni** [comment]
Can just use the clone name, as thats something both would have access to. Definitely not ideal but it would work. Can technically use the start async call and maybe make a self-watchdog. When we want the async VI to stop we start a timer. If the timer runs out, the VI aborts itself.
